/// Named route identifiers for GoRouter.
abstract final class RoutePaths {
  static const String splash = 'splash';
  static const String login = 'login';
  static const String signup = 'signup';
  static const String forgotPassword = 'forgot-password';
  static const String dashboard = 'dashboard';
  static const String goals = 'goals';
  static const String goalCreate = 'goal-create';
  static const String goalEdit = 'goal-edit';
  static const String projects = 'projects';
  static const String projectCreate = 'project-create';
  static const String projectDetail = 'project-detail';
  static const String projectEdit = 'project-edit';
  static const String tasks = 'tasks';
  static const String taskCreate = 'task-create';
  static const String taskEdit = 'task-edit';
  static const String calendar = 'calendar';
  static const String calendarCreate = 'calendar-create';
  static const String calendarEdit = 'calendar-edit';
  static const String meetings = 'meetings';
  static const String meetingCreate = 'meeting-create';
  static const String meetingDetail = 'meeting-detail';
  static const String meetingEdit = 'meeting-edit';
  static const String crm = 'crm';
  static const String notes = 'notes';
  static const String documents = 'documents';
  static const String analytics = 'analytics';
  static const String notifications = 'notifications';
  static const String settings = 'settings';
  static const String profile = 'profile';
}
